#!/usr/bin/python3
# -*- coding: utf-8 -*-
from selenium.webdriver.firefox.webdriver import WebDriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

success = True
wd = WebDriver()
wd.implicitly_wait(60)
wd.get("http://localhost:3000/")
print("Esperando a que cargue...")
#time.sleep(10) # seconds
if not ("subject" in wd.find_element_by_tag_name("html").text):
    success = False
    print("verifyTextPresent failed")
wd.find_element_by_css_selector("a[href='#toc']").click()
time.sleep(2)
wd.find_element_by_css_selector("a[data-group-layer-on='sedes']").click()
time.sleep(2)
wd.find_element_by_css_selector("a[data-group-layer-off='sedes']").click()
time.sleep(2)
wd.find_element_by_css_selector("i[data-layer-icon='construccion']").click()
wd.find_element_by_css_selector("i[data-layer-icon='construccion']").click()
wd.find_element_by_css_selector("i[data-layer-icon='nivel']").click()
wd.find_element_by_css_selector("i[data-layer-icon='nivel']").click()
wd.find_element_by_css_selector("i[data-layer-icon='sede_punto']").click()
wd.find_element_by_css_selector("i[data-layer-icon='sede_punto']").click()
wd.find_element_by_css_selector("i[data-layer-icon='zonas_exteriores']").click()
wd.find_element_by_css_selector("i[data-layer-icon='zonas_exteriores']").click()
wd.find_element_by_xpath("//div[@id='toc-div']/ul/li[1]/div[2]/ul/li[2]/a/i").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-7e283500-16b9-e4f3-7e49-63c172b666af']//span[.='Piso 8']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-7e283500-16b9-e4f3-7e49-63c172b666af']//span[.='Piso 7']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-7e283500-16b9-e4f3-7e49-63c172b666af']//span[.='Piso 6']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-7e283500-16b9-e4f3-7e49-63c172b666af']//span[.='Piso 5']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-7e283500-16b9-e4f3-7e49-63c172b666af']//span[.='Piso 4']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-7e283500-16b9-e4f3-7e49-63c172b666af']//span[.='Piso 3']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-7e283500-16b9-e4f3-7e49-63c172b666af']//span[.='Piso 2']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-7e283500-16b9-e4f3-7e49-63c172b666af']//span[.='Piso 1']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-7e283500-16b9-e4f3-7e49-63c172b666af']//span[.='Semisótano']").click()
wd.find_element_by_xpath("//div[@id='toc-div']/ul/li[1]/div[2]/ul/li[3]/a/i").click()
wd.find_element_by_css_selector("canvas.ol-unselectable").click()
wd.find_element_by_link_text("Acercar").click()
wd.find_element_by_xpath("//div[@id='toc-div']/ul/li[2]/div[1]").click()
wd.find_element_by_xpath("//div[@id='toc-div']/ul/li[2]/div[2]/ul/li/a/i").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-38b10192-24d6-a9a6-da9a-88083bfefb7b']//span[.='Piso 8']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-38b10192-24d6-a9a6-da9a-88083bfefb7b']//span[.='Piso 7']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-38b10192-24d6-a9a6-da9a-88083bfefb7b']//span[.='Piso 5']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-38b10192-24d6-a9a6-da9a-88083bfefb7b']//span[.='Piso 3']").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-38b10192-24d6-a9a6-da9a-88083bfefb7b']//span[.='Piso SS']").click()
wd.find_element_by_xpath("//div[@id='toc-div']/ul/li[3]/div[1]").click()
wd.find_element_by_xpath("//div[@id='toc-div']/ul/li[3]/div[2]/ul/li[1]/a/i").click()
wd.find_element_by_xpath("//div[@id='toc-div']/ul/li[3]/div[2]/ul/li[2]/a/i").click()
wd.find_element_by_xpath("//div[@id='toc-div']/ul/li[3]/div[2]/ul/li[3]/a/i").click()
wd.find_element_by_xpath("//div[@id='toc-div']/ul/li[3]/div[2]/ul/li[4]/a/i").click()
wd.find_element_by_link_text("search").click()
wd.find_element_by_id("quick_query_value").click()
wd.find_element_by_id("quick_query_value").clear()
wd.find_element_by_id("quick_query_value").send_keys("calle 40")
wd.find_element_by_id("quick_query_button").click()
wd.find_element_by_link_text("Acercar a").click()
wd.find_element_by_css_selector("canvas.ol-unselectable").click()
wd.find_element_by_css_selector("canvas.ol-unselectable").click()
wd.find_element_by_css_selector("canvas.ol-unselectable").click()
wd.find_element_by_link_text("insert_drive_file").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-ae30c5f4-a432-e165-3f7b-af5d36b1d65c']/li[2]/span").click()
wd.find_element_by_xpath("//div[@id='contenido-charts']/div[2]/button").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-ae30c5f4-a432-e165-3f7b-af5d36b1d65c']/li[2]/span").click()
wd.find_element_by_xpath("//div[@id='contenido-charts']/div[2]/button").click()
wd.find_element_by_link_text("ACEPTAR").click()
wd.find_element_by_xpath("//div[@id='contenido-charts']/div[4]/button").click()
wd.find_element_by_css_selector("input.select-dropdown.active").click()
wd.find_element_by_xpath("//ul[@id='select-options-ae30c5f4-a432-e165-3f7b-af5d36b1d65c']/li[2]/span").click()
wd.find_element_by_link_text("list").click()
wd.find_element_by_link_text("help_outline").click()
wd.find_element_by_link_text("insert_drive_file").click()
wd.find_element_by_xpath("//div[@id='contenido-charts']/div[2]/button").click()
wd.find_element_by_link_text("ACEPTAR").click()
wd.find_element_by_css_selector("i.fa.fa-info").click()
wd.find_element_by_css_selector("canvas.ol-unselectable").click()
wd.find_element_by_xpath("//div[@id='resultadosDiv']//a[.='Acercar a']").click()
wd.quit()
if not success:
    raise Exception("Test failed.")
